<a href="https://colab.research.google.com/github/Esantomi/Chatbot/blob/main/DART_API.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install opendartreader # DART API 사용 패키지

Collecting opendartreader
  Downloading OpenDartReader-0.1.1-py3-none-any.whl (18 kB)
Collecting requests-file
  Downloading requests_file-1.5.1-py2.py3-none-any.whl (3.7 kB)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (2.23.0)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.1.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from opendartreader) (4.2.6)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->opendartreader) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2021.5.30)
ERROR: Operation cancelled by user

In [ ]:
pip install --upgrade opendartreader # 이미 설치돼 있다면 업그레이드

Requirement already satisfied: opendartreader in /usr/local/lib/python3.7/dist-packages (0.1.1)
Requirement already satisfied: requests-file in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.5.1)
Requirement already satisfied: requests>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (2.23.0)
Requirement already satisfied: pandas>=0.19.2 in /usr/local/lib/python3.7/dist-packages (from opendartreader) (1.1.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from opendartreader) (4.2.6)
Requirement already satisfied: numpy>=1.15.4 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (1.19.5)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.19.2->opendartreader) (2.8.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.19.2->opendartreader) (1.15.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.3.0->opendartreader) (2021.5.30)

# 0. 객체 생성

In [ ]:
import OpenDartReader

api_key = '6a3f3ae274882cecf0fef08389b93ce53f7390bd'
# opendart.fss.or.kr에서 발급받은 key

# 객체 생성 (API KEY 지정)
dart = OpenDartReader(api_key)

# 1. 공시 정보 검색

In [ ]:
# 삼성전자의 정기보고서('A') 2019년
dart.list('005930', kind='A', start='2020-01-01', end='2020-12-31')

  corp_code corp_name stock_code corp_cls  ...        rcept_no flr_nm  rcept_dt rm
0  00126380      삼성전자     005930        Y  ...  20201116001248   삼성전자  20201116
1  00126380      삼성전자     005930        Y  ...  20200814001766   삼성전자  20200814
2  00126380      삼성전자     005930        Y  ...  20200515001451   삼성전자  20200515
3  00126380      삼성전자     005930        Y  ...  20200330003851   삼성전자  20200330  연

[4 rows x 9 columns]

In [ ]:
# 기업의 개황 정보
dart.company('005930')

{'acc_mt': '12',
 'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
 'bizr_no': '1248100998',
 'ceo_nm': '김기남, 김현석, 고동진',
 'corp_cls': 'Y',
 'corp_code': '00126380',
 'corp_name': '삼성전자(주)',
 'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
 'est_dt': '19690113',
 'fax_no': '031-200-7538',
 'hm_url': 'www.sec.co.kr',
 'induty_code': '264',
 'ir_url': '',
 'jurir_no': '1301110006246',
 'message': '정상',
 'phn_no': '031-200-1114',
 'status': '000',
 'stock_code': '005930',
 'stock_name': '삼성전자'}

In [ ]:
# 회사명에 삼성전자가 포함된 회사들에 대한 개황 정보
dart.company_by_name('삼성전자')

[{'acc_mt': '12',
  'adres': '경기도 수원시 영통구 중부대로 324 (매탄동, KT동수원지사)',
  'bizr_no': '7898701103',
  'ceo_nm': '정석진',
  'corp_cls': 'E',
  'corp_code': '01345812',
  'corp_name': '삼성전자서비스씨에스 주식회사',
  'corp_name_eng': 'SAMSUNG ELECTRONICS SERVICE CUSTOMER SATISFACTION., LTD.',
  'est_dt': '20181105',
  'fax_no': '031-8006-1009',
  'hm_url': '',
  'induty_code': '75991',
  'ir_url': '',
  'jurir_no': '1358110352541',
  'message': '정상',
  'phn_no': '031-210-8938',
  'status': '000',
  'stock_code': '',
  'stock_name': '삼성전자서비스씨에스'},
 {'acc_mt': '12',
  'adres': '경기도 수원시 영통구 삼성로 290 (원천동)',
  'bizr_no': '1248158485',
  'ceo_nm': '심원환',
  'corp_cls': 'E',
  'corp_code': '00258999',
  'corp_name': '삼성전자 서비스주식회사',
  'corp_name_eng': 'SAMSUNNG ELECTRONICS SERVICE CO., LTD',
  'est_dt': '19981027',
  'fax_no': '031-270-2106',
  'hm_url': 'www.samsungsvc.co.kr',
  'induty_code': '95',
  'ir_url': '',
  'jurir_no': '1301110049139',
  'message': '정상',
  'phn_no': '031-270-2177',
  'status': '000',
  'stock_code': '',
  'stock_name': '삼성전자서비스'},
 {'acc_mt': '12',
  'adres': '경기도 성남시 분당구 황새울로 340',
  'bizr_no': '6178117517',
  'ceo_nm': '이평우',
  'corp_cls': 'E',
  'corp_code': '00252074',
  'corp_name': '삼성전자판매 주식회사',
  'corp_name_eng': 'SAMSUNG ELECTRONICS SALES Co., Ltd.',
  'est_dt': '19960711',
  'fax_no': '02-3460-6802',
  'hm_url': 'www.samsungsales.co.kr',
  'induty_code': '47320',
  'ir_url': '',
  'jurir_no': '1801110210300',
  'message': '정상',
  'phn_no': '02-3460-6656',
  'status': '000',
  'stock_code': '',
  'stock_name': '삼성전자판매'},
 {'acc_mt': '12',
  'adres': '경기도 수원시 영통구 삼성로 129',
  'bizr_no': '1248155381',
  'ceo_nm': '최윤범',
  'corp_cls': 'E',
  'corp_code': '00366997',
  'corp_name': '삼성전자로지텍(주)',
  'corp_name_eng': 'SELC.CO.,LTD',
  'est_dt': '19980401',
  'fax_no': '031-270-3673',
  'hm_url': 'www.selc.co.kr',
  'induty_code': '52999',
  'ir_url': '',
  'jurir_no': '1301110046797',
  'message': '정상',
  'phn_no': '031-270-3488',
  'status': '000',
  'stock_code': '',
  'stock_name': '삼성전자로지텍'},
 {'acc_mt': '12',
  'adres': '경기도 수원시 영통구  삼성로 129 (매탄동)',
  'bizr_no': '1248100998',
  'ceo_nm': '김기남, 김현석, 고동진',
  'corp_cls': 'Y',
  'corp_code': '00126380',
  'corp_name': '삼성전자(주)',
  'corp_name_eng': 'SAMSUNG ELECTRONICS CO,.LTD',
  'est_dt': '19690113',
  'fax_no': '031-200-7538',
  'hm_url': 'www.sec.co.kr',
  'induty_code': '264',
  'ir_url': '',
  'jurir_no': '1301110006246',
  'message': '정상',
  'phn_no': '031-200-1114',
  'status': '000',
  'stock_code': '005930',
  'stock_name': '삼성전자'}]

In [ ]:
# 삼성전자 사업보고서 (2018.12) 원문 텍스트
xml_text = dart.document('20190401004781')

# 2. 사업 보고서

In [ ]:
# 삼성전자(005930), 배당관련 사항, 2018년
dart.report('005930', '배당', 2018)

          rcept_no corp_cls corp_code  ...      frmtrm        lwfr stock_knd
0   20190401004781        Y  00126380  ...       5,000       5,000       NaN
1   20190401004781        Y  00126380  ...  41,344,569  22,415,655       NaN
2   20190401004781        Y  00126380  ...  28,800,837  11,579,749       NaN
3   20190401004781        Y  00126380  ...     299,868     157,967       NaN
4   20190401004781        Y  00126380  ...   5,826,302   3,991,892       NaN
5   20190401004781        Y  00126380  ...           -           -       NaN
6   20190401004781        Y  00126380  ...       14.10       17.80       NaN
7   20190401004781        Y  00126380  ...        1.70        1.60       보통주
8   20190401004781        Y  00126380  ...        2.10        2.00       우선주
9   20190401004781        Y  00126380  ...           -           -       보통주
10  20190401004781        Y  00126380  ...           -           -       우선주
11  20190401004781        Y  00126380  ...      42,500      28,500       보통주
12  20190401004781        Y  00126380  ...      42,550      28,550       우선주
13  20190401004781        Y  00126380  ...           -           -       보통주
14  20190401004781        Y  00126380  ...           -           -       우선주

[15 rows x 9 columns]

In [ ]:
# 서울반도체(046890), 최대주주 관한 사항, 2018년
dart.report('046890', '최대주주', 2018)

         rcept_no corp_cls  ... trmend_posesn_stock_co trmend_posesn_stock_qota_rt
0  20190401003450        K  ...              9,749,744                       16.72
1  20190401003450        K  ...              5,076,358                        8.71
2  20190401003450        K  ...              5,076,358                        8.71
3  20190401003450        K  ...             19,902,460                       34.13
4  20190401003450        K  ...                      -                           -

[5 rows x 12 columns]

In [ ]:
# 서울반도체(046890), 임원 관한 사항, 2018년
dart.report('046890', '임원', 2018)

         rcept_no corp_cls  ... hffc_pd  tenure_end_on
0  20190401003450        K  ...  1992년~  2019년 03월 28일
1  20190401003450        K  ...  2016년~  2020년 03월 27일
2  20190401003450        K  ...  2018년~  2020년 03월 27일
3  20190401003450        K  ...  2018년~  2020년 03월 27일

[4 rows x 15 columns]

# 3. 상장기업 재무정보

In [ ]:
# 삼성전자 2018 재무제표 
dart.finstate('삼성전자', 2018) # 사업보고서

          rcept_no reprt_code  ...     bfefrmtrm_amount ord
0   20190401004781      11011  ...  141,429,704,000,000   1
1   20190401004781      11011  ...  120,744,620,000,000   3
2   20190401004781      11011  ...  262,174,324,000,000   5
3   20190401004781      11011  ...   54,704,095,000,000   7
4   20190401004781      11011  ...   14,507,196,000,000   9
5   20190401004781      11011  ...   69,211,291,000,000  11
6   20190401004781      11011  ...      897,514,000,000  13
7   20190401004781      11011  ...  193,086,317,000,000  17
8   20190401004781      11011  ...  192,963,033,000,000  21
9   20190401004781      11011  ...  201,866,745,000,000  23
10  20190401004781      11011  ...   29,240,672,000,000  25
11  20190401004781      11011  ...   30,713,652,000,000  27
12  20190401004781      11011  ...   22,726,092,000,000  29
13  20190401004781      11011  ...   69,981,128,000,000   2
14  20190401004781      11011  ...  104,821,831,000,000   4
15  20190401004781      11011  ...  174,802,959,000,000   6
16  20190401004781      11011  ...   34,076,122,000,000   8
17  20190401004781      11011  ...    3,180,075,000,000  10
18  20190401004781      11011  ...   37,256,197,000,000  12
19  20190401004781      11011  ...      897,514,000,000  15
20  20190401004781      11011  ...  140,747,574,000,000  19
21  20190401004781      11011  ...  137,546,762,000,000  22
22  20190401004781      11011  ...  133,947,204,000,000  24
23  20190401004781      11011  ...   13,647,436,000,000  26
24  20190401004781      11011  ...   14,725,074,000,000  28
25  20190401004781      11011  ...   11,579,749,000,000  30

[26 rows x 20 columns]

In [ ]:
# 삼성전자 2018Q1 재무제표
dart.finstate('삼성전자', 2018, reprt_code='11013')

          rcept_no reprt_code  ...   thstrm_add_amount   frmtrm_add_amount
0   20180515001699      11013  ...                 NaN                 NaN
1   20180515001699      11013  ...                 NaN                 NaN
2   20180515001699      11013  ...                 NaN                 NaN
3   20180515001699      11013  ...                 NaN                 NaN
4   20180515001699      11013  ...                 NaN                 NaN
5   20180515001699      11013  ...                 NaN                 NaN
6   20180515001699      11013  ...                 NaN                 NaN
7   20180515001699      11013  ...                 NaN                 NaN
8   20180515001699      11013  ...                 NaN                 NaN
9   20180515001699      11013  ...  60,563,714,000,000  50,547,526,000,000
10  20180515001699      11013  ...  15,642,170,000,000   9,898,361,000,000
11  20180515001699      11013  ...  16,175,907,000,000  10,164,576,000,000
12  20180515001699      11013  ...  11,688,544,000,000   7,684,354,000,000
13  20180515001699      11013  ...                 NaN                 NaN
14  20180515001699      11013  ...                 NaN                 NaN
15  20180515001699      11013  ...                 NaN                 NaN
16  20180515001699      11013  ...                 NaN                 NaN
17  20180515001699      11013  ...                 NaN                 NaN
18  20180515001699      11013  ...                 NaN                 NaN
19  20180515001699      11013  ...                 NaN                 NaN
20  20180515001699      11013  ...                 NaN                 NaN
21  20180515001699      11013  ...                 NaN                 NaN
22  20180515001699      11013  ...  42,606,978,000,000  34,578,524,000,000
23  20180515001699      11013  ...  11,200,897,000,000   5,675,571,000,000
24  20180515001699      11013  ...  11,568,977,000,000   6,309,744,000,000
25  20180515001699      11013  ...   8,452,458,000,000   4,873,767,000,000

[26 rows x 19 columns]

In [ ]:
# 여러종목 한번에
dart.finstate('00126380,00164779,00164742', 2018)
dart.finstate('005930, 000660, 005380', 2018)
dart.finstate('삼성전자, SK하이닉스, 현대자동차', 2018)

          rcept_no reprt_code  ...     bfefrmtrm_amount ord
0   20190401004781      11011  ...  141,429,704,000,000   1
1   20190401004781      11011  ...  120,744,620,000,000   3
2   20190401004781      11011  ...  262,174,324,000,000   5
3   20190401004781      11011  ...   54,704,095,000,000   7
4   20190401004781      11011  ...   14,507,196,000,000   9
..             ...        ...  ...                  ...  ..
71  20190404002329      11011  ...   23,091,513,000,000  22
72  20190404002329      11011  ...   16,733,111,000,000  24
73  20190404002329      11011  ...    3,012,419,000,000  26
74  20190404002329      11011  ...    2,961,742,000,000  28
75  20190404002329      11011  ...    2,655,022,000,000  30

[76 rows x 20 columns]

In [ ]:
# 단일기업 전체 재무제표 (삼성전자 2018 전체 재무제표)
dart.finstate_all('005930', 2018)

           rcept_no reprt_code bsns_year  ... bfefrmtrm_amount ord thstrm_add_amount
0    20190401004781      11011      2018  ...  141429704000000   1               NaN
1    20190401004781      11011      2018  ...   32111442000000   2               NaN
2    20190401004781      11011      2018  ...   52432411000000   3               NaN
3    20190401004781      11011      2018  ...    3638460000000   4               NaN
4    20190401004781      11011      2018  ...                    5               NaN
..              ...        ...       ...  ...              ...  ..               ...
213  20190401004781      11011      2018  ...  -11934586000000  19               NaN
214  20190401004781      11011      2018  ...     -28810000000  19               NaN
215  20190401004781      11011      2018  ...  193086317000000  19               NaN
216  20190401004781      11011      2018  ...     897514000000  19               NaN
217  20190401004781      11011      2018  ...    4403893000000  19               NaN

[218 rows x 17 columns]

In [ ]:
# 재무제표 XBRL 원본 파일 저장 (삼성전자 2018 사업보고서)
dart.finstate_xml('20190401004781', save_as='삼성전자_2018_사업보고서_XBRL.zip')

True

In [ ]:
# XBRL 표준계정과목체계(계정과목)
dart.xbrl_taxonomy('BS1')

    sj_div   bsns_de  ...                                           ifrs_ref data_tp
0      BS1  20180701  ...                                                        NaN
1      BS1  20180701  ...                                                        NaN
2      BS1  20180701  ...                                  K-IFRS 1001 문단 60       X
3      BS1  20180701  ...            K-IFRS 1001 문단 54 (9),K-IFRS 1007 문단 45       X
4      BS1  20180701  ...            K-IFRS 1001 문단 54 (9),K-IFRS 1007 문단 45       X
..     ...       ...  ...                                                ...     ...
514    BS1  20180701  ...  K-IFRS 1001 문단 54 (18),K-IFRS 1001 문단 78 (5),K...       X
515    BS1  20180701  ...  K-IFRS 1001 문단 54 (18),K-IFRS 1001 문단 78 (5),K...       X
516    BS1  20180701  ...                             K-IFRS 1001 문단 54 (17)       X
517    BS1  20180701  ...                                                        NaN
518    BS1  20180701  ...                                                        NaN

[519 rows x 8 columns]

In [ ]:
# 임원ㆍ주요주주 소유보고 (종목코드, 종목명, 고유번호 모두 지정 가능)
dart.major_shareholders_exec('005930')

           rcept_no    rcept_dt  ... sp_stock_lmp_rate sp_stock_lmp_irds_rate
0    20190723000260  2019-07-23  ...              0.00                   0.00
1    20190723000287  2019-07-23  ...              0.00                   0.00
2    20190729000265  2019-07-29  ...              0.00                   0.00
3    20190805000185  2019-08-05  ...              0.00                   0.00
4    20190814001161  2019-08-14  ...              9.01                   9.01
..              ...         ...  ...               ...                    ...
200  20210603000241  2021-06-03  ...              0.00                   0.00
201  20210624000396  2021-06-24  ...              0.00                   0.00
202  20210629000122  2021-06-29  ...              0.00                   0.00
203  20210629000190  2021-06-29  ...              0.00                   0.00
204  20210723000157  2021-07-23  ...              0.00                   0.00

[205 rows x 12 columns]

# 5. 확장 기능

In [ ]:
# 지정한 날짜의 공시목록 전체
dart.list_date('2020-02-03')

/usr/local/lib/python3.7/dist-packages/OpenDartReader/dart.py:132: UserWarning: list_date() is deprecated. list_date_ex()를 사용하세요
  warnings.warn('list_date() is deprecated. list_date_ex()를 사용하세요')

In [ ]:
# 지정한 날짜의 공시목록 전체 (시간 정보 포함)
dart.list_date_ex('2020-01-03')

              rcept_dt corp_cls  ...    flr_nm                 rm
0  2020-01-03 18:40:00     유가증권  ...       풀무원     한국거래소 유가증권시장본부
1  2020-01-03 18:26:00      코스닥  ...     이엠앤아이               정정신고
2  2020-01-03 18:25:00      코스닥  ...     이엠앤아이               정정신고
3  2020-01-03 18:25:00      코스닥  ...     이엠앤아이               정정신고
4  2020-01-03 18:20:00      코넥스  ...      렌딩머신  본 문서는 한국거래소 코넥스시장
..                 ...      ...  ...       ...                ...
76 2020-01-03 07:30:00     기타법인  ...  예교지성회계법인
77 2020-01-03 07:30:00      코스닥  ...       김병혁
78 2020-01-03 07:30:00      코스닥  ...       이흥복
79 2020-01-03 07:30:00      코스닥  ...       포티스               정정신고
80 2020-01-03 07:30:00      코스닥  ...       포티스               정정신고

[581 rows x 8 columns]

In [ ]:
# 개별 문서 제목과 URL
rcp_no = '20190401004781' # 삼성전자 2018년 사업보고서
dart.sub_docs(rcp_no)

                          title                                                url
0                     사 업 보 고 서  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
1                【 대표이사 등의 확인 】  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
2                     I. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
3                     1. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
4                     2. 회사의 연혁  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
5                   3. 자본금 변동사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
6                   4. 주식의 총수 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
7                     5. 의결권 현황  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
8                6. 배당에 관한 사항 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
9                    II. 사업의 내용  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
10               III. 재무에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
11                    1. 요약재무정보  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
12                    2. 연결재무제표  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
13                 3. 연결재무제표 주석  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
14                      4. 재무제표  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
15                   5. 재무제표 주석  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
16              6. 기타 재무에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
17          IV. 이사의 경영진단 및 분석의견  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
18               V. 감사인의 감사의견 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
19      VI. 이사회 등 회사의 기관에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
20                1. 이사회에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
21               2. 감사제도에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
22         3. 주주의 의결권 행사에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
23               VII. 주주에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
24       VIII. 임원 및 직원 등에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
25               1. 임원 및 직원의 현황  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
26                  2. 임원의 보수 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
27            IX. 계열회사 등에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
28              X. 이해관계자와의 거래내용  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
29  XI. 그 밖에 투자자 보호를 위하여 필요한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
30                  【 전문가의 확인 】  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
31                   1. 전문가의 확인  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
32                2. 전문가와의 이해관계  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...

In [ ]:
# 제목이 잘 매치되는 순서로 소트
dart.sub_docs('20190401004781', match='사업의 내용')

                          title                                                url
9                    II. 사업의 내용  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
2                     I. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
3                     1. 회사의 개요  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
4                     2. 회사의 연혁  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
28              X. 이해관계자와의 거래내용  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
1                【 대표이사 등의 확인 】  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
18               V. 감사인의 감사의견 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
0                     사 업 보 고 서  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
31                   1. 전문가의 확인  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
17          IV. 이사의 경영진단 및 분석의견  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
6                   4. 주식의 총수 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
30                  【 전문가의 확인 】  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
26                  2. 임원의 보수 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
32                2. 전문가와의 이해관계  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
19      VI. 이사회 등 회사의 기관에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
25               1. 임원 및 직원의 현황  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
14                      4. 재무제표  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
22         3. 주주의 의결권 행사에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
12                    2. 연결재무제표  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
11                    1. 요약재무정보  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
7                     5. 의결권 현황  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
15                   5. 재무제표 주석  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
5                   3. 자본금 변동사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
13                 3. 연결재무제표 주석  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
20                1. 이사회에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
8                6. 배당에 관한 사항 등  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
23               VII. 주주에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
10               III. 재무에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
21               2. 감사제도에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
16              6. 기타 재무에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
27            IX. 계열회사 등에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
24       VIII. 임원 및 직원 등에 관한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...
29  XI. 그 밖에 투자자 보호를 위하여 필요한 사항  http://dart.fss.or.kr/report/viewer.do?rcpNo=2...

In [ ]:
# 첨부 문서 제목과 URL
dart.attach_doc_list(rcp_no)

                        title                                                url
0            2019.04.01 감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
1         2019.04.01 감사의감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
2  2019.04.01 내부감시장치에대한감사의의견서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
3    2019.04.01 내부회계관리제도운영보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
4          2019.04.01 연결감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
5            2019.04.01 영업보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
6               2019.04.01 정관  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...

In [ ]:
# 제목이 잘 매치되는 순서로 소트
dart.attach_doc_list(rcp_no, match='감사보고서')

                        title                                                url
0            2019.04.01 감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
4          2019.04.01 연결감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
1         2019.04.01 감사의감사보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
5            2019.04.01 영업보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
3    2019.04.01 내부회계관리제도운영보고서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
2  2019.04.01 내부감시장치에대한감사의의견서  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...
6               2019.04.01 정관  http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...